/**
 * The single implementation of "what did the server actually say?".
 *
 * ── Why this file exists ───────────────────────────────────────────
 *
 * This function used to be copy-pasted, byte for byte, into four
 * tutoring2 admin views (Leads, PayoutRates, PayoutRequests,
 * PayoutSettings — ten call sites between them). Fixing the leak
 * described below in one copy would have left four implementations
 * that silently disagree, with nothing to tell the next reader which
 * one is authoritative. It lives here instead so there is exactly one.
 *
 * ── What it does ───────────────────────────────────────────────────
 *
 * The tutoring2 services post with a bare axios call and the http
 * interceptor re-rejects the raw AxiosError (src/lib/http.ts), so
 * `(e as Error).message` at a call site is axios's own "Request failed
 * with status code 422" and the server's explanation is never read.
 * The explanation lives at `response.data`.
 *
 * Laravel's `ValidationException::summarize()` copies the FIRST error
 * string into the top-level `message` (appending "(and N more errors)"
 * when several fields failed), so `message` is both the richer field
 * and the house precedence. The `errors` bag is the fallback for
 * responses that populate only one or the other.
 *
 * Returns null when there is no server-authored text to show, so the
 * caller keeps ownership of its own fallback ladder.
 *
 * ── Why some statuses are refused outright ─────────────────────────
 *
 * `message` is NOT always author-written. On the statuses below it is
 * generated by the framework and describes internals, not the user's
 * problem. Verified against this backend (Laravel 12, stock exception
 * rendering — there is no app/Exceptions/Handler.php and no `renderable`.
 * Checked against the file prod actually runs: the shadow
 * bootstrap/app.php that docker-compose.prod.yml bind-mounts over the
 * repo copy registers only a `reportable` log-shipper, and `reportable`
 * does not affect the rendered response — so rendering is stock in prod
 * too. The repo's own bootstrap/app.php wires Sentry, but it is inert
 * in prod and says nothing about prod behaviour):
 *
 *   404  ModelNotFoundException's message is carried verbatim into
 *        NotFoundHttpException, and because that IS an HttpException,
 *        `convertExceptionToArray` returns it even with APP_DEBUG off.
 *        The admin is shown
 *          "No query results for model
 *           [App\Modules\Tutoring\Models\Lead] 01a0…"
 *        — the internal PHP class path. Reached whenever a list is
 *        stale: admin B deletes the row, admin A acts on it.
 *
 *   5xx  With debug off the body is the literal string "Server Error";
 *        with debug on (local, CI, any staging built that way) it is
 *        the raw exception text, which for a QueryException includes
 *        the SQL and the table names. Neither belongs on screen.
 *
 * Everything else keeps its body, deliberately. A status allow-list —
 * "trust the body only on 422" — was considered and rejected: it would
 * suppress real, user-facing Indonesian text that this backend returns
 * on other statuses, turning a fix into a regression. Concretely, and
 * all of these are live on the ten call sites:
 *
 *   402  "Modul \"Bimbel\" belum aktif untuk sekolah Anda. Aktifkan
 *        untuk menggunakan fitur ini." — EnsureModuleEntitled, which
 *        wraps the whole `tutoring-v2` route group. The one message an
 *        admin most needs to read, and the most actionable.
 *   409  "Hanya pengajuan berstatus pending yang dapat disetujui." and
 *        four siblings in the payout-request actions, thrown as
 *        HttpResponseException so the body is literal.
 *   403  "Anda tidak memiliki akses ke pengajuan honor." and
 *        "Akun Anda tidak terhubung dengan profil tutor di tenant
 *        ini." — PayoutRequestController.
 *   400  "Tenant tidak terdefinisi."
 *
 * (A 403 raised by a bare `$this->authorize()` — which is what the
 * Leads endpoints use — carries Laravel's English default "This action
 * is unauthorized." instead. That is unhelpful but it is not a leak of
 * internals, and it is what those screens show today. It is left alone
 * rather than special-cased, so this rule stays a statement about
 * which statuses expose internals rather than a list of strings to
 * pattern-match. A literal blocklist was the other candidate and was
 * rejected: it cannot cover the debug-on 5xx case, whose text is
 * arbitrary and unenumerable.)
 *
 * An unrecognised or absent status is TRUSTED, which is the previous
 * behaviour — this rule only ever subtracts, never invents.
 */

type ErrorBody = {
  message?: string;
  errors?: Record<string, string[]>;
};

type RejectedRequest = {
  response?: {
    status?: number;
    data?: ErrorBody;
  };
};

/**
 * True when a body's `message` on this status is framework-generated
 * rather than author-written. See the file header for the evidence.
 */
function bodyDescribesInternals(status: number | undefined): boolean {
  if (typeof status !== 'number') return false;
  return status === 404 || status >= 500;
}

export function extractError(e: unknown): string | null {
  const err = e as RejectedRequest;
  const response = err?.response;

  // No response at all = the request never completed (axios builds a
  // network/timeout AxiosError with no `response` — verified in
  // axios/lib/adapters/xhr.js, which passes only 4 constructor args).
  // Returning null hands an offline failure to the caller's transport
  // rung, so it still reads exactly as it does today.
  if (!response) return null;

  if (bodyDescribesInternals(response.status)) return null;

  const msg = response.data?.message;
  if (msg) return msg;

  const errors = response.data?.errors;
  if (errors) {
    const first = Object.values(errors)[0];
    if (Array.isArray(first) && first.length > 0) return first[0];
  }
  return null;
}
