// Part of the AppLocalizations API — i18n sweep additions for lesson_plans.
part of 'language_utils.dart';

// ── lesson_plans (auto-generated from i18n sweep) ───────────────────
const kLesPlaRegenerateAiTitle = {'en': 'Regenerate AI', 'id': 'Generate Ulang AI'};
const kLesPlaRegenerateAiSubtitle = {'en': 'Reorganize the lesson plan content with additional instructions', 'id': 'Susun ulang konten RPP dengan instruksi tambahan'};
const kLesPlaRegenerateDescription = {'en': 'The system will reorganize the lesson plan content based on current data. You can add specific instructions below.', 'id': 'Sistem akan menyusun ulang konten RPP berdasarkan data saat ini. Anda dapat menambahkan instruksi spesifik di bawah.'};
const kLesPlaChapter = {'en': 'Chapter', 'id': 'Bab'};
const kLesPlaAdditionalInstructions = {'en': 'Additional Instructions / Prompt (Optional)', 'id': 'Instruksi / Prompt Tambahan (Opsional)'};
const kLesPlaLimitReached = {'en': 'Limit Reached', 'id': 'Batas Tercapai'};
const kLesPlaUnderstood = {'en': 'Understood', 'id': 'Mengerti'};
const kLesPlaDetails = {'en': 'Lesson Plan Details', 'id': 'Detail RPP'};
const kLesPlaApprove = {'en': 'Approve Lesson Plan', 'id': 'Setujui RPP'};
const kLesPlaReject = {'en': 'Reject Lesson Plan', 'id': 'Tolak RPP'};
const kLesPlaNoTitle = {'en': 'Lesson Plan without title', 'id': 'RPP tanpa judul'};
const kLesPlaContents = {'en': 'Lesson Plan Contents', 'id': 'Isi RPP'};
const kLesPlaSectionsFilled = {'en': 'sections filled', 'id': 'bagian terisi'};
const kLesPlaK13Section = {'en': 'K13 Section', 'id': 'Bagian K13'};
const kLesPlaModulAjarSection = {'en': 'Teaching Module Section', 'id': 'Bagian Modul Ajar'};
const kLesPlaCoreComponents = {'en': 'core components', 'id': 'komponen inti'};
// TODO(i18n): review auto-translated EN
const kLesPlaK13 = {'en': 'K13 Curriculum', 'id': 'K13'};
const kLesPlaOnePage = {'en': 'One-Page Lesson Plan', 'id': 'RPP 1 Halaman'};
const kLesPlaTeachingModule = {'en': 'Teaching Module', 'id': 'Modul Ajar'};
// TODO(i18n): review auto-translated EN
const kLesPlaUploadFile = {'en': 'Upload File', 'id': 'Upload File'};
const kLesPlaApproveConfirm = {'en': 'Approve this lesson plan?', 'id': 'Setujui RPP ini?'};
const kLesPlaApproveSubtitle = {'en': 'Status changes to Approved & teacher receives notification.', 'id': 'Status berubah menjadi Disetujui & guru menerima notifikasi.'};
const kLesPlaRejectSubtitle = {'en': 'Status becomes Rejected. Teacher must recreate the lesson plan.', 'id': 'Status menjadi Ditolak. Guru harus membuat ulang RPP.'};
const kLesPlaRejectReasonKd = {'en': 'Does not match KD / CP', 'id': 'Tidak sesuai KD / CP'};
const kLesPlaRejectReasonSmart = {'en': 'Objectives lack SMART criteria', 'id': 'Tujuan kurang SMART'};
const kLesPlaRejectReasonAssessment = {'en': 'Assessment is incomplete', 'id': 'Penilaian kurang lengkap'};
const kLesPlaRejectReasonTimeAlloc = {'en': 'Time allocation is not realistic', 'id': 'Alokasi waktu tidak realistis'};
const kLesPlaRejectReasonDuplicate = {'en': 'Duplicate with another lesson plan', 'id': 'Duplikat dengan RPP lain'};
const kLesPlaRejectReasonFormat = {'en': 'Format does not match', 'id': 'Format tidak sesuai'};
const kLesPlaSubjectTeacher = {'en': 'Subject Teacher', 'id': 'Guru Mata Pelajaran'};
const kLesPlaRemainingRegens = {'en': 'Remaining regenerations:', 'id': 'Sisa regenerasi:'};
const kLesPlaAddInstructionsPrompt = {'en': 'Add specific instructions (optional) to guide AI when regenerating this section.', 'id': 'Tambahkan instruksi spesifik (opsional) untuk memandu AI saat membuat ulang bagian ini.'};
const kLesPlaRegenerateAllFields = {'en': 'Regenerate All Fields', 'id': 'Regenerasi Semua Field'};
const kLesPlaRegenerateAllSubtitle = {'en': 'Each field has its own regeneration limit.', 'id': 'Setiap field memiliki batas regenerasi masing-masing.'};
const kLesPlaRegenerateAllWarning = {'en': 'All sections of the lesson plan will be regenerated by AI. Unsaved changes in each section will be overwritten.', 'id': 'Seluruh bagian RPP akan dibuat ulang oleh AI. Perubahan yang belum disimpan pada setiap bagian akan ditimpa.'};
const kLesPlaRegenerateFieldLimit = {'en': 'Regeneration limit for', 'id': 'Batas regenerasi untuk'};
