// Admin "Tolak RPP" sheet — Mockup Frame C1.
//
// Replaces the older AppAlertDialog reject prompt that used to live
// inside LessonPlanAdminActionBar. The sheet adds:
//   - a summary card so the admin double-checks they're on the right RPP,
//   - multi-select alasan chips so the catatan starts with a structured
//     reason and the admin only types the specifics,
//   - a "ditolak bersifat final" notice so the difference between Tolak
//     (final) and Kembalikan (revision) is visible BEFORE the action.
//
// Returns a [LessonPlanRejectResult] when the admin confirms or null
// on cancel.
import 'package:flutter/material.dart';

import 'package:manajemensekolah/core/utils/color_utils.dart';
import 'package:manajemensekolah/core/widgets/app_bottom_sheet.dart';
import 'package:manajemensekolah/core/widgets/bottom_sheet_footer.dart';

class LessonPlanRejectResult {
  final String note;
  final List<String> reasons; // pre-selected chip labels (informational)
  const LessonPlanRejectResult({required this.note, required this.reasons});
}

/// Canonical alasan-penolakan chips. Tapping a chip prepends the
/// label to the catatan textarea so the resulting note reads as a
/// structured list of issues the admin observed.
const List<String> _kRejectReasons = [
  'Tidak sesuai KD / CP',
  'Tujuan kurang SMART',
  'Penilaian kurang lengkap',
  'Alokasi waktu tidak realistis',
  'Duplikat dengan RPP lain',
  'Format tidak sesuai',
];

Future<LessonPlanRejectResult?> showLessonPlanAdminRejectSheet({
  required BuildContext context,
  required String title,
  required String formatLabel,
  required String subjectLabel,
  required String classLabel,
  required String teacherName,
  String? initialNote,
}) {
  return AppBottomSheet.show<LessonPlanRejectResult>(
    context: context,
    title: 'Tolak RPP',
    subtitle: 'Status menjadi Ditolak. Guru harus membuat ulang RPP.',
    icon: Icons.cancel_rounded,
    primaryColor: ColorUtils.error600,
    content: _RejectSheetBody(
      title: title,
      formatLabel: formatLabel,
      subjectLabel: subjectLabel,
      classLabel: classLabel,
      teacherName: teacherName,
      initialNote: initialNote,
    ),
  );
}

class _RejectSheetBody extends StatefulWidget {
  final String title;
  final String formatLabel;
  final String subjectLabel;
  final String classLabel;
  final String teacherName;
  final String? initialNote;

  const _RejectSheetBody({
    required this.title,
    required this.formatLabel,
    required this.subjectLabel,
    required this.classLabel,
    required this.teacherName,
    this.initialNote,
  });

  @override
  State<_RejectSheetBody> createState() => _RejectSheetBodyState();
}

class _RejectSheetBodyState extends State<_RejectSheetBody> {
  late final TextEditingController _ctrl;
  final Set<String> _selectedReasons = <String>{};

  @override
  void initState() {
    super.initState();
    _ctrl = TextEditingController(text: widget.initialNote ?? '');
  }

  @override
  void dispose() {
    _ctrl.dispose();
    super.dispose();
  }

  bool get _canSubmit => _ctrl.text.trim().length >= 3;

  void _toggleReason(String reason) {
    setState(() {
      if (_selectedReasons.contains(reason)) {
        _selectedReasons.remove(reason);
      } else {
        _selectedReasons.add(reason);
      }
      // Mirror selection into the textarea — only when the user hasn't
      // typed their own custom note yet. Once they start editing freely
      // we leave it alone so chip toggles don't blow away their text.
      final autoNote = _selectedReasons.join(' · ');
      if (_ctrl.text.trim().isEmpty ||
          _isAutoGenerated(_ctrl.text.trim())) {
        _ctrl.text = autoNote;
        _ctrl.selection = TextSelection.collapsed(offset: _ctrl.text.length);
      }
    });
  }

  /// Heuristic — the current textarea contents look auto-generated if
  /// they consist purely of chip labels joined with " · ". If the
  /// admin added free text the textarea is treated as custom and not
  /// overwritten by chip toggles.
  bool _isAutoGenerated(String text) {
    if (text.isEmpty) return true;
    final parts = text.split(' · ').map((e) => e.trim()).toSet();
    return parts.every(_kRejectReasons.contains);
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      mainAxisSize: MainAxisSize.min,
      children: [
        _summaryCard(),
        const SizedBox(height: 14),
        Text(
          'Alasan penolakan',
          style: TextStyle(
            fontSize: 11,
            fontWeight: FontWeight.w700,
            color: ColorUtils.slate700,
          ),
        ),
        const SizedBox(height: 6),
        Wrap(
          spacing: 6,
          runSpacing: 6,
          children: _kRejectReasons
              .map(
                (r) => _ReasonChip(
                  label: r,
                  selected: _selectedReasons.contains(r),
                  onTap: () => _toggleReason(r),
                ),
              )
              .toList(),
        ),
        const SizedBox(height: 12),
        Row(
          children: [
            Text(
              'Catatan untuk guru',
              style: TextStyle(
                fontSize: 11,
                fontWeight: FontWeight.w700,
                color: ColorUtils.slate700,
              ),
            ),
            const SizedBox(width: 4),
            Text(
              '*',
              style: TextStyle(
                fontSize: 11,
                color: ColorUtils.error600,
                fontWeight: FontWeight.w800,
              ),
            ),
          ],
        ),
        const SizedBox(height: 6),
        TextField(
          controller: _ctrl,
          maxLines: 4,
          onChanged: (_) => setState(() {}),
          textInputAction: TextInputAction.newline,
          decoration: InputDecoration(
            hintText: 'Apa yang perlu diperbaiki guru?',
            hintStyle: TextStyle(color: ColorUtils.slate400, fontSize: 12),
            filled: true,
            fillColor: ColorUtils.slate50,
            contentPadding: const EdgeInsets.all(12),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(10),
              borderSide: BorderSide(color: ColorUtils.slate200),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(10),
              borderSide: BorderSide(color: ColorUtils.slate200),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(10),
              borderSide: BorderSide(color: ColorUtils.error600, width: 1.4),
            ),
          ),
        ),
        const SizedBox(height: 12),
        _finalNotice(),
        const SizedBox(height: 14),
        BottomSheetFooter(
          primaryLabel: 'Tolak RPP',
          secondaryLabel: 'Batal',
          primaryColor: ColorUtils.error600,
          primaryEnabled: _canSubmit,
          onPrimary: () => Navigator.of(context).pop(
            LessonPlanRejectResult(
              note: _ctrl.text.trim(),
              reasons: _selectedReasons.toList(),
            ),
          ),
          onSecondary: () => Navigator.of(context).pop(),
        ),
      ],
    );
  }

  Widget _summaryCard() {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
      decoration: BoxDecoration(
        color: ColorUtils.slate50,
        borderRadius: BorderRadius.circular(10),
        border: Border.all(color: ColorUtils.slate200),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            '${widget.formatLabel.toUpperCase()} · ${widget.subjectLabel}',
            style: TextStyle(
              fontSize: 10,
              fontWeight: FontWeight.w700,
              color: ColorUtils.slate500,
              letterSpacing: 0.5,
            ),
          ),
          const SizedBox(height: 2),
          Text(
            widget.title,
            style: TextStyle(
              fontSize: 13,
              fontWeight: FontWeight.w800,
              color: ColorUtils.slate900,
              height: 1.3,
            ),
            maxLines: 2,
            overflow: TextOverflow.ellipsis,
          ),
          const SizedBox(height: 4),
          Text(
            '${widget.classLabel} · ${widget.teacherName}',
            style: TextStyle(
              fontSize: 11,
              color: ColorUtils.slate500,
              fontWeight: FontWeight.w600,
            ),
          ),
        ],
      ),
    );
  }

  Widget _finalNotice() {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
      decoration: BoxDecoration(
        color: const Color(0xFFFEE2E2),
        border: Border.all(color: const Color(0xFFFECACA)),
        borderRadius: BorderRadius.circular(10),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(
            Icons.warning_amber_rounded,
            size: 18,
            color: ColorUtils.error600,
          ),
          const SizedBox(width: 8),
          Expanded(
            child: RichText(
              text: TextSpan(
                style: TextStyle(
                  fontSize: 11,
                  color: ColorUtils.error600,
                  height: 1.45,
                  fontWeight: FontWeight.w600,
                ),
                children: const [
                  TextSpan(
                    text: 'RPP ditolak bersifat final. ',
                    style: TextStyle(fontWeight: FontWeight.w800),
                  ),
                  TextSpan(
                    text:
                        'Guru harus membuat RPP baru — bukan revisi. '
                        'Gunakan "Kembalikan ke guru" untuk meminta revisi '
                        'tanpa membuang versi ini.',
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _ReasonChip extends StatelessWidget {
  final String label;
  final bool selected;
  final VoidCallback onTap;

  const _ReasonChip({
    required this.label,
    required this.selected,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    // Mockup `.reason-chip` uses a **dashed** outline when unselected
    // and a solid red-tinted border when selected. Flutter's
    // BorderSide doesn't support dashed natively, so wrap the unselected
    // state in a DottedBorder-style CustomPaint via DashedRect helper.
    // For compatibility (no extra dependency), we approximate with a
    // dashed-effect via overlay tint — close enough at 1px width.
    return Material(
      color: Colors.transparent,
      child: InkWell(
        borderRadius: BorderRadius.circular(999),
        onTap: onTap,
        child: Container(
          padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
          decoration: BoxDecoration(
            color: selected ? const Color(0xFFFEE2E2) : ColorUtils.slate50,
            borderRadius: BorderRadius.circular(999),
            border: Border.all(
              color: selected
                  ? ColorUtils.error700.withValues(alpha: 0.25)
                  : ColorUtils.slate300,
              width: 1,
            ),
          ),
          child: Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              if (selected) ...[
                Icon(
                  Icons.check_rounded,
                  size: 12,
                  color: ColorUtils.error700,
                ),
                const SizedBox(width: 4),
              ],
              Text(
                label,
                style: TextStyle(
                  fontSize: 10.5,
                  fontWeight: FontWeight.w700,
                  color: selected ? ColorUtils.error700 : ColorUtils.slate600,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
